on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
      with: # Set Azure credentials secret as an input
        credentials: ${{ secrets.AZURML }}
      env: # Or as an environment variable
        credentials: ${{ secrets.AZURML }}
        
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
          inlineScript: Get-AzVM -ResourceGroupName "tt_resource_group"
          azPSVersion: 3.1.0
