on: [push]

name: AzureLoginSample
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
      uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURML }}
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
          inlineScript: Get-AzVM -ResourceGroupName "tt_resource_group"
          azPSVersion: 3.1.0
